### ISSUE TITLE
Error on config read on standard readme execution

### ISSUE THREAD

**Issue by ms0uto** [antonioalfa22/GoGin-API-REST-Template#1]
Hello there, i was playing around trying the "template" and got two different problems in Debian.
First, with current trunk state following standard readme instructions i got: 
'/bin/sh -c go mod download' returned a non-zero code: 1. during docker build  .  -t api-rest

Secondly, i bypassed previous 'dependecy' problem updating to latest alpine image version
on Dockerfile:  golang:1.15.3-alpine3.12
after that, all goes smoothly until you get execution error
can't read cofig file './cmd/api/config.yml'

May you have a look?

**Comment by antoniopaya22** [comment]
I just fixed the error in the last commit. Check that it works well for you.

**Comment by ms0uto** [comment]
Antonio sé que es bastante tarde (porque se me olvidó responder) pero gracias por mirarlo
en su momento! Me sirvió!
Ahora ando retomando un poco Go (suelo trabajar con Java y Python) y estaba mirando
mis cosas y por eso volví a ver ésto jaja

Un saludo y gracias!
